server:
  port: 12345
eureka:
  client:
    service-url:
      defaultZone: http://test-eureka.baijia.com/eureka
spring:
  application:
    name: mocker
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    root: INFO
    org.springframework.web.servlet: DEBUG
